- name: Create Sensor Server folder in /opt/
  ansible.builtin.file:
    path: /opt/sensor_server
    state: directory
    owner: pi
    group: pi
    mode: 0774

- name: Create Sensor Server folder in /var/opt/
  ansible.builtin.file:
    path: /var/opt/sensor_server
    state: directory
    owner: pi
    group: pi
    mode: 0774

- name: Copy Sensor Server files and folders
  ansible.builtin.copy:
    src: ../files/sensor_server
    dest: /opt/
    owner: pi
    group: pi
    mode: 0754