---
all:
  hosts:
  children:
    sensors:
      hosts:
        pi-sensor01:
          ansible_host: 172.16.32.27
    controllers:
      hosts:
        pi-controller01:
          ansible_host: 172.16.32.139